import { CrudConfig } from "./pages/CrudPage";

const boolBadge = (v: any, yesClass = "bg-green-500/20 text-green-400", noClass = "bg-gray-600/20 text-gray-400") => (
  <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${v ? yesClass : noClass}`}>
    {v ? "Yes" : "No"}
  </span>
);

const jsonPreview = (v: any) => (
  <span className="text-xs text-gray-500">{v ? JSON.stringify(v).slice(0, 40) : "-"}</span>
);

export const crudConfigs: CrudConfig[] = [
  {
    key: "classes",
    title: "Classes",
    columns: [
      { key: "name", label: "Name", render: (v) => <span className="font-medium text-white">{v}</span> },
      { key: "role", label: "Role" },
      { key: "element", label: "Element" },
      { key: "rarity", label: "Rarity" },
      { key: "requiredLevel", label: "Min Level" },
      {
        key: "isStarter",
        label: "Starter",
        render: (v) => boolBadge(v, "bg-accent-500/20 text-accent-400", "bg-gray-600/20 text-gray-400"),
      },
      { key: "isActive", label: "Active", render: (v) => boolBadge(v) },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "slug", label: "Slug", type: "text", placeholder: "e.g. cavaleiro", hint: "Lowercase, no spaces" },
      { name: "description", label: "Description", type: "textarea", required: true },
      { name: "lore", label: "Lore", type: "textarea" },
      { name: "icon", label: "Icon", type: "text", placeholder: "e.g. 'Swords'" },
      {
        name: "element",
        label: "Element",
        type: "select",
        required: true,
        defaultValue: "neutral",
        options: ["fire", "water", "earth", "wind", "light", "dark", "neutral"],
      },
      {
        name: "rarity",
        label: "Rarity",
        type: "select",
        required: true,
        defaultValue: "common",
        options: ["common", "uncommon", "rare", "epic", "legendary", "mythic"],
      },
      {
        name: "difficulty",
        label: "Difficulty",
        type: "select",
        required: true,
        defaultValue: "easy",
        options: ["easy", "medium", "hard", "expert"],
      },
      {
        name: "role",
        label: "Role",
        type: "select",
        required: true,
        defaultValue: "hybrid",
        options: ["tank", "support", "mage", "dps", "assassin", "hybrid"],
      },
      {
        name: "statModel",
        label: "Stat Model",
        type: "select",
        defaultValue: "hybrid",
        options: ["tank", "hybrid", "luckHybrid", "powerCaster", "physicalDPS", "magicDPS", "support", "assassin", "bruiser", "battleMage"],
      },
      { name: "requiredLevel", label: "Required Level", type: "number", defaultValue: 1 },
      { name: "isStarter", label: "Starter Class (available on character creation)", type: "boolean", defaultValue: false },
      { name: "isActive", label: "Active", type: "boolean", defaultValue: true },
    ],
  },
  {
    key: "items",
    title: "Items",
    columns: [
      { key: "name", label: "Name", render: (v) => <span className="font-medium text-white">{v}</span> },
      { key: "type", label: "Type" },
      { key: "rarity", label: "Rarity" },
      { key: "level", label: "Level" },
      { key: "tier", label: "Tier" },
      { key: "isActive", label: "Active", render: (v) => boolBadge(v) },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea", required: true },
      { name: "icon", label: "Icon", type: "text" },
      { name: "type", label: "Type", type: "text", required: true, placeholder: "weapon, armor, consumable, material..." },
      { name: "subtype", label: "Subtype", type: "text", placeholder: "sword, potion, helmet..." },
      { name: "rarity", label: "Rarity", type: "select", required: true, defaultValue: "common", options: ["common", "uncommon", "rare", "epic", "legendary", "mythic"] },
      { name: "level", label: "Level", type: "number", defaultValue: 1 },
      { name: "tier", label: "Tier", type: "number", defaultValue: 1 },
      { name: "buyPrice", label: "Buy Price", type: "number", defaultValue: 0 },
      { name: "sellPrice", label: "Sell Price", type: "number", defaultValue: 0 },
      { name: "stats", label: "Stats", type: "json", jsonSchema: { mode: "record", keyPlaceholder: "stat (ex: attack)", valueType: "number", valuePlaceholder: "valor" }, hint: "Ex: attack, defense, magic, speed" },
      { name: "requirements", label: "Requirements", type: "json", jsonSchema: { mode: "record", keyPlaceholder: "requisito (ex: level)", valueType: "number", valuePlaceholder: "valor" }, hint: "Ex: level, strength" },
      { name: "effects", label: "Effects", type: "json", jsonSchema: { mode: "record", keyPlaceholder: "efeito (ex: heal)", valueType: "number", valuePlaceholder: "valor" }, hint: "Ex: heal, manaRestore, shield" },
      { name: "isTradable", label: "Tradable", type: "boolean", defaultValue: true },
      { name: "isSellable", label: "Sellable", type: "boolean", defaultValue: true },
      { name: "isStackable", label: "Stackable", type: "boolean", defaultValue: false },
      { name: "isActive", label: "Active", type: "boolean", defaultValue: true },
    ],
  },
  {
    key: "monsters",
    title: "Monsters / Bosses",
    columns: [
      { key: "name", label: "Name", render: (v) => <span className="font-medium text-white">{v}</span> },
      { key: "level", label: "Level" },
      { key: "hp", label: "HP" },
      { key: "attack", label: "Attack" },
      { key: "isElite", label: "Elite", render: (v) => boolBadge(v) },
      { key: "isBoss", label: "Boss", render: (v) => boolBadge(v, "bg-red-500/20 text-red-400") },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea", required: true },
      { name: "imageUrl", label: "Image URL", type: "text" },
      { name: "level", label: "Level", type: "number", defaultValue: 1 },
      { name: "hp", label: "HP", type: "number", defaultValue: 50 },
      { name: "mana", label: "Mana", type: "number", defaultValue: 20 },
      { name: "attack", label: "Attack", type: "number", defaultValue: 10 },
      { name: "defense", label: "Defense", type: "number", defaultValue: 5 },
      { name: "magic", label: "Magic", type: "number", defaultValue: 5 },
      { name: "magicDefense", label: "Magic Defense", type: "number", defaultValue: 5 },
      { name: "speed", label: "Speed", type: "number", defaultValue: 10 },
      { name: "xpReward", label: "XP Reward", type: "number", defaultValue: 10 },
      { name: "goldReward", label: "Gold Reward", type: "number", defaultValue: 5 },
      { name: "isElite", label: "Elite", type: "boolean", defaultValue: false },
      { name: "isBoss", label: "Boss", type: "boolean", defaultValue: false },
      { name: "faction", label: "Faction", type: "text" },
      { name: "element", label: "Element", type: "text" },
    ],
  },
  {
    key: "maps",
    title: "Maps",
    columns: [
      { key: "name", label: "Name", render: (v) => <span className="font-medium text-white">{v}</span> },
      { key: "slug", label: "Slug", render: (v) => <span className="text-xs text-gray-500">{v}</span> },
      { key: "region", label: "Region" },
      { key: "requiredLevel", label: "Min Level" },
      { key: "isPvPZone", label: "PvP", render: (v) => boolBadge(v) },
      { key: "isActive", label: "Active", render: (v) => boolBadge(v) },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "slug", label: "Slug", type: "text", required: true, hint: "Unique, lowercase" },
      { name: "description", label: "Description", type: "textarea", required: true },
      { name: "imageUrl", label: "Image URL", type: "text" },
      { name: "region", label: "Region", type: "text", required: true },
      { name: "requiredLevel", label: "Required Level", type: "number", defaultValue: 1 },
      { name: "sortOrder", label: "Sort Order", type: "number", defaultValue: 0 },
      { name: "isPvPZone", label: "PvP Zone", type: "boolean", defaultValue: false },
      { name: "isActive", label: "Active", type: "boolean", defaultValue: true },
    ],
  },
  {
    key: "quests",
    title: "Quests",
    columns: [
      { key: "title", label: "Title", render: (v) => <span className="font-medium text-white">{v}</span> },
      { key: "type", label: "Type" },
      { key: "difficulty", label: "Difficulty" },
      { key: "requiredLevel", label: "Min Level" },
      { key: "isRepeatable", label: "Repeatable", render: (v) => boolBadge(v) },
      { key: "isActive", label: "Active", render: (v) => boolBadge(v) },
    ],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea", required: true },
      { name: "type", label: "Type", type: "text", required: true, placeholder: "main, side, daily, event..." },
      { name: "difficulty", label: "Difficulty", type: "select", defaultValue: "easy", options: ["easy", "medium", "hard", "expert"] },
      { name: "requiredLevel", label: "Required Level", type: "number", defaultValue: 1 },
      { name: "xpReward", label: "XP Reward", type: "number", defaultValue: 0 },
      { name: "goldReward", label: "Gold Reward", type: "number", defaultValue: 0 },
      { name: "objectives", label: "Objectives", type: "json", jsonSchema: { mode: "object-array", addLabel: "Adicionar objetivo", fields: [
          { name: "type", label: "Tipo", type: "select", options: ["kill", "collect", "talk", "reach", "use", "escort", "defeat_boss"] },
          { name: "monsterName", label: "Alvo (nome ou ID)", type: "text", placeholder: "ex: Rato da Floresta" },
          { name: "amount", label: "Quantidade", type: "number" },
        ] } },
      { name: "itemRewards", label: "Item Rewards", type: "json", jsonSchema: { mode: "object-array", addLabel: "Adicionar recompensa", fields: [
          { name: "itemId", label: "Item ID", type: "text" },
          { name: "itemName", label: "Nome do Item", type: "text" },
          { name: "quantity", label: "Quantidade", type: "number" },
        ] } },
      { name: "isRepeatable", label: "Repeatable", type: "boolean", defaultValue: false },
      { name: "isActive", label: "Active", type: "boolean", defaultValue: true },
      { name: "sortOrder", label: "Sort Order", type: "number", defaultValue: 0 },
    ],
  },
  {
    key: "buffs",
    title: "Buffs / Debuffs",
    columns: [
      { key: "name", label: "Name", render: (v) => <span className="font-medium text-white">{v}</span> },
      { key: "type", label: "Type" },
      { key: "duration", label: "Duration (ms)", render: (v) => <span className="font-mono text-xs">{v ?? 0}</span> },
      { key: "maxStacks", label: "Max Stacks" },
      { key: "statModifiers", label: "Stat Modifiers", render: jsonPreview },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea", required: true },
      { name: "type", label: "Type", type: "text", required: true, placeholder: "buff, debuff, dot, hot..." },
      { name: "icon", label: "Icon", type: "text" },
      { name: "duration", label: "Duration (ms)", type: "number", defaultValue: 0 },
      { name: "maxStacks", label: "Max Stacks", type: "number", defaultValue: 1 },
      { name: "tickInterval", label: "Tick Interval (ms)", type: "number", defaultValue: 0 },
      { name: "tickEffect", label: "Tick Effect", type: "text", placeholder: "damage, heal..." },
      { name: "statModifiers", label: "Stat Modifiers", type: "json", jsonSchema: { mode: "record", keyPlaceholder: "stat (ex: attack)", valueType: "number", valuePlaceholder: "valor (pode ser negativo)" }, hint: "Ex: attack, defense, speed" },
      { name: "specialEffect", label: "Special Effect", type: "text" },
      { name: "stackBehavior", label: "Stack Behavior", type: "select", defaultValue: "independent", options: ["independent", "overwrite", "refresh", "accumulate"] },
    ],
  },
  {
    key: "races",
    title: "Races",
    columns: [
      { key: "name", label: "Name", render: (v) => <span className="font-medium text-white">{v}</span> },
      { key: "slug", label: "Slug", render: (v) => <span className="text-xs text-gray-500">{v}</span> },
      { key: "description", label: "Description", render: (v) => <span className="text-gray-400 max-w-xs truncate block">{v}</span> },
      { key: "traits", label: "Modifiers", render: jsonPreview },
      { key: "isActive", label: "Active", render: (v) => boolBadge(v) },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "slug", label: "Slug", type: "text", required: true, hint: "Unique, lowercase" },
      { name: "description", label: "Description", type: "textarea", required: true },
      {
        name: "traits",
        label: "Stat Modifiers",
        type: "json",
        jsonSchema: { mode: "record", keyPlaceholder: "stat (ex: baseHp)", valueType: "number", valuePlaceholder: "valor" },
        hint: "Ex: baseHp, baseAttack, baseSpeed, manaRecovery",
      },
      { name: "isActive", label: "Active", type: "boolean", defaultValue: true },
    ],
  },
  {
    key: "traits",
    title: "Traits",
    columns: [
      { key: "name", label: "Name", render: (v) => <span className="font-medium text-white">{v}</span> },
      { key: "slug", label: "Slug", render: (v) => <span className="text-xs text-gray-500">{v}</span> },
      { key: "description", label: "Description", render: (v) => <span className="text-gray-400 max-w-xs truncate block">{v}</span> },
      { key: "modifiers", label: "Modifiers", render: jsonPreview },
      { key: "isActive", label: "Active", render: (v) => boolBadge(v) },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "slug", label: "Slug", type: "text", required: true, hint: "Unique, lowercase" },
      { name: "description", label: "Description", type: "textarea", required: true },
      {
        name: "modifiers",
        label: "Modifiers",
        type: "json",
        jsonSchema: { mode: "record", keyPlaceholder: "modificador (ex: xpBonus)", valueType: "number", valuePlaceholder: "percentual (%)" },
        hint: "Ex: xpBonus, goldBonus, critBonus, cooldownReduction (em %)",
      },
      { name: "isActive", label: "Active", type: "boolean", defaultValue: true },
    ],
  },
];
