import { AppDataSource } from '../connection';

export async function seedItems(): Promise<void> {
  const queryRunner = AppDataSource.createQueryRunner();
  await queryRunner.connect();

  try {
    await queryRunner.query(`TRUNCATE TABLE "items" CASCADE`);

    const items = [
      {
        name: 'Rusty Sword',
        description: 'A worn iron sword that has seen better days. It will serve a novice well.',
        type: 'WEAPON',
        rarity: 'COMMON',
        level: 1,
        tier: 1,
        stats: '{"attackPower": 5}',
        requirements: '{}',
        sell_price: 10,
        buy_price: 50,
        is_tradable: true,
        is_soulbound: false,
        max_stack: 1,
        durability: 50,
        max_durability: 50,
        element: 'NORMAL',
      },
      {
        name: 'Wooden Shield',
        description: 'A simple wooden shield reinforced with iron bands.',
        type: 'WEAPON',
        rarity: 'COMMON',
        level: 1,
        tier: 1,
        stats: '{"defense": 8, "block": 0.05}',
        requirements: '{}',
        sell_price: 15,
        buy_price: 75,
        is_tradable: true,
        is_soulbound: false,
        max_stack: 1,
        durability: 60,
        max_durability: 60,
        element: 'NORMAL',
      },
      {
        name: 'Apprentice Wand',
        description: 'A basic wooden wand channeling minor arcane energy.',
        type: 'WEAPON',
        rarity: 'COMMON',
        level: 1,
        tier: 1,
        stats: '{"magicPower": 6}',
        requirements: '{}',
        sell_price: 12,
        buy_price: 60,
        is_tradable: true,
        is_soulbound: false,
        max_stack: 1,
        durability: 40,
        max_durability: 40,
        element: 'ARCANE',
      },
      {
        name: 'Leather Helmet',
        description: 'A basic leather cap offering minimal protection.',
        type: 'HELMET',
        rarity: 'COMMON',
        level: 1,
        tier: 1,
        stats: '{"defense": 3, "hp": 10}',
        requirements: '{}',
        sell_price: 8,
        buy_price: 40,
        is_tradable: true,
        is_soulbound: false,
        max_stack: 1,
        durability: 40,
        max_durability: 40,
        element: 'NORMAL',
      },
      {
        name: 'Linen Robe',
        description: 'A comfortable linen robe favored by magic practitioners.',
        type: 'CHESTPLATE',
        rarity: 'COMMON',
        level: 1,
        tier: 1,
        stats: '{"defense": 2, "magicDefense": 5, "mp": 20}',
        requirements: '{}',
        sell_price: 10,
        buy_price: 50,
        is_tradable: true,
        is_soulbound: false,
        max_stack: 1,
        durability: 35,
        max_durability: 35,
        element: 'NORMAL',
      },
      {
        name: 'Iron Chestplate',
        description: 'A sturdy iron chestplate that provides solid protection.',
        type: 'CHESTPLATE',
        rarity: 'UNCOMMON',
        level: 5,
        tier: 2,
        stats: '{"defense": 15, "hp": 30, "strength": 2}',
        requirements: '{"level": 5, "strength": 10}',
        sell_price: 50,
        buy_price: 250,
        is_tradable: true,
        is_soulbound: false,
        max_stack: 1,
        durability: 80,
        max_durability: 80,
        element: 'NORMAL',
      },
      {
        name: 'Healing Herb',
        description: 'A common herb with minor healing properties. Restores 30 HP.',
        type: 'CONSUMABLE',
        rarity: 'COMMON',
        level: 1,
        tier: 1,
        stats: '{"healing": 30}',
        requirements: '{}',
        sell_price: 2,
        buy_price: 10,
        is_tradable: true,
        is_soulbound: false,
        max_stack: 99,
        durability: 0,
        max_durability: 0,
        element: 'NORMAL',
      },
      {
        name: 'Mana Leaf',
        description: 'A shimmering blue leaf that restores 20 MP when consumed.',
        type: 'CONSUMABLE',
        rarity: 'COMMON',
        level: 1,
        tier: 1,
        stats: '{"mp": 20}',
        requirements: '{}',
        sell_price: 3,
        buy_price: 15,
        is_tradable: true,
        is_soulbound: false,
        max_stack: 99,
        durability: 0,
        max_durability: 0,
        element: 'NORMAL',
      },
      {
        name: 'Copper Ore',
        description: 'A raw copper ore used in crafting and smithing.',
        type: 'MATERIAL',
        rarity: 'COMMON',
        level: 1,
        tier: 1,
        stats: '{}',
        requirements: '{}',
        sell_price: 5,
        buy_price: 25,
        is_tradable: true,
        is_soulbound: false,
        max_stack: 999,
        durability: 0,
        max_durability: 0,
        element: 'NORMAL',
      },
      {
        name: 'Silver Ring of Protection',
        description: 'A finely crafted silver ring imbued with protective enchantments.',
        type: 'RING',
        rarity: 'RARE',
        level: 10,
        tier: 3,
        stats: '{"defense": 8, "magicDefense": 8, "hp": 50, "vitality": 3}',
        requirements: '{"level": 10}',
        sell_price: 200,
        buy_price: 1000,
        is_tradable: true,
        is_soulbound: false,
        max_stack: 1,
        durability: 100,
        max_durability: 100,
        element: 'NORMAL',
      },
      {
        name: 'Copper Dagger',
        description: 'A sharp copper dagger. Quick and effective.',
        type: 'WEAPON',
        rarity: 'COMMON',
        level: 2,
        tier: 1,
        stats: '{"attackPower": 8, "dexterity": 1}',
        requirements: '{}',
        sell_price: 20,
        buy_price: 100,
        is_tradable: true,
        is_soulbound: false,
        max_stack: 1,
        durability: 45,
        max_durability: 45,
        element: 'NORMAL',
      },
      {
        name: 'Novice Boots',
        description: 'Simple leather boots for new adventurers.',
        type: 'BOOTS',
        rarity: 'COMMON',
        level: 1,
        tier: 1,
        stats: '{"defense": 2, "agility": 1}',
        requirements: '{}',
        sell_price: 8,
        buy_price: 35,
        is_tradable: true,
        is_soulbound: false,
        max_stack: 1,
        durability: 35,
        max_durability: 35,
        element: 'NORMAL',
      },
    ];

    for (const item of items) {
      await queryRunner.query(
        `INSERT INTO "items" (name, description, type, rarity, level, tier, stats, requirements, sell_price, buy_price, is_tradable, is_soulbound, max_stack, durability, max_durability, element)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)`,
        [item.name, item.description, item.type, item.rarity, item.level, item.tier, item.stats, item.requirements, item.sell_price, item.buy_price, item.is_tradable, item.is_soulbound, item.max_stack, item.durability, item.max_durability, item.element]
      );
    }

    console.log('Items seeded successfully');
  } finally {
    await queryRunner.release();
  }
}

if (require.main === module) {
  AppDataSource.initialize()
    .then(() => seedItems())
    .then(() => process.exit(0))
    .catch((err) => { console.error(err); process.exit(1); });
}
